
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHelloObjis", targetNamespace = "http://service.demowebservice.ensup.eu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHelloObjis {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reponse", partName = "reponse")
    @Action(input = "http://service.demowebservice.ensup.eu/IHelloObjis/ditBonjourRequest", output = "http://service.demowebservice.ensup.eu/IHelloObjis/ditBonjourResponse")
    public String ditBonjour(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
